os: linux
files:
   - source: https://s3-us-west-2.amazonaws.com/qa-jenkins-release/bm-api-prod.war
     destination: /usr/share/tomcat7/webapps/app.war
permissions:
   - object: /usr/share/tomcat7/webapps/app.war
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: codeDeployScripts/stopTomcat.sh
      runas: root
   AfterInstall:
    - location: codeDeployScripts/startTomcat.sh
      runas: root
